import { z } from 'zod'

export const kenBurnsSchema = z.union([
  z.enum(['in', 'out']),
  z.object({
    zoom: z.enum(['in', 'out']),
    pan: z.enum(['none', 'left', 'right', 'up', 'down']),
  }),
])
export type KenBurns = z.infer<typeof kenBurnsSchema>

/**
 * Remotion passes RAW input props (zod validates, never transforms) — always
 * normalize at the use-site; undefined-safe for props written pre-expansion.
 */
export function normalizeKenBurns(v: KenBurns | undefined): { zoom: 'in' | 'out', pan: 'none' | 'left' | 'right' | 'up' | 'down' } {
  if (v === undefined)
    return { zoom: 'in', pan: 'none' }
  return typeof v === 'string' ? { zoom: v, pan: 'none' } : v
}

export const clipSchema = z.object({
  /** Filename under video/public/ (Remotion staticFile). */
  src: z.string(),
  /** `video` plays the file; `image` shows a still with a slow Ken Burns push. */
  kind: z.enum(['video', 'image']),
  durationInFrames: z.number().int().positive(),
  /**
   * `full` = full-bleed cover (needs a true 9:16 source clip).
   * `framed` = editorial card on the dark brand ground — native aspect, no
   * quality-destroying crop; use for landscape clips.
   */
  layout: z.enum(['full', 'framed']),
  /** Width/height of the source clip — sizes the framed card. */
  aspect: z.number().positive(),
  /** Uppercase chip above a framed card (e.g. "THE SHOWCASE STANDARD"). */
  label: z.string().nullable(),
  /** Card treatment when layout is `framed` — see variation-axes.md. */
  cardStyle: z.enum(['native', 'polaroid', 'split', 'letterbox', 'offset']).default('native'),
  /** Second source for `cardStyle: 'split'` (src = BEFORE half, secondarySrc = AFTER half). */
  secondarySrc: z.string().nullable().default(null),
  /** Ken Burns for `kind: 'image'`: legacy string or `{ zoom, pan }` object. */
  kenBurns: kenBurnsSchema.default('in'),
  /**
   * How this clip enters (ONE transition family per reel — variation-axes.md).
   * `none` = hard cut, reserved for the snap moment.
   */
  transitionIn: z.enum(['none', 'fade', 'whip', 'wipe', 'dissolve', 'zoomPunch']).default('none'),
  /** Motion direction for whip/wipe. */
  transitionDirection: z.enum(['left', 'right', 'up', 'down']).default('left'),
})

export const captionSchema = z.object({
  /** `*word*` marks the emphasis word (brand blue + scale); max one per line. */
  text: z.string(),
  startFrame: z.number().int().min(0),
  endFrame: z.number().int().min(1),
})

/** Punch-in: hard 1-frame scale jump on the clips layer, decaying back over ~10f. */
export const punchInSchema = z.object({
  frame: z.number().int().min(0),
  /** 1.10–1.15 hard, ≤1.20 (digital zoom quality ceiling). */
  scale: z.number().min(1).max(1.2),
})

/** SFX cue — transient must land ON the visual hit frame (editing-patterns.md). */
export const sfxSchema = z.object({
  src: z.string(),
  frame: z.number().int().min(0),
  volume: z.number().min(0).max(1),
})

/**
 * Opening brand moment: lockup springs in centered over the cold-open shot,
 * then glides in one continuous motion into the watermark slot, where the
 * persistent watermark takes over on the landing frame (dockFrame + 15).
 */
export const logoIntroSchema = z.object({
  /** Full lockup art — use the same file as watermarkSrc for a seamless dock. */
  src: z.string(),
  enterFrame: z.number().int().min(0),
  dockFrame: z.number().int().min(0),
})

/** Word caption (@remotion/captions shape) — generated by scripts/transcribe.mjs. */
export const wordCaptionSchema = z.object({
  text: z.string(),
  startMs: z.number(),
  endMs: z.number(),
  timestampMs: z.number().nullable(),
  confidence: z.number().nullable(),
  /** Marked `*word*` in the VO script — renders in the luxe serif + brand blue. */
  emphasis: z.boolean().default(false),
})

export const showcaseReelSchema = z.object({
  clips: z.array(clipSchema).min(1),
  /** Kinetic hook headline; shows hookStartFrame → hookStartFrame + hookDurationInFrames. */
  hook: z.string(),
  hookStartFrame: z.number().int().min(0).default(0),
  hookDurationInFrames: z.number().int().positive().default(75),
  /** Hook text treatment — one of the variation-axis menu (axis 1). */
  hookStyle: z.enum(['wordStagger', 'punch', 'freeze', 'typewriter']).default('wordStagger'),
  /** Checkmark rows shown above the framed card of clips[checkmarkClipIndex]. */
  checkmarks: z.array(z.string()).max(4),
  checkmarkClipIndex: z.number().int().nullable(),
  /** Burned-in captions mirroring the voiceover (most viewers watch muted). */
  captions: z.array(captionSchema),
  /**
   * Word-level captions (whisper-timed via scripts/transcribe.mjs). When
   * non-empty they REPLACE `captions` with CapCut-style karaoke pages —
   * timing comes from the audio itself, so drift is impossible.
   */
  wordCaptions: z.array(wordCaptionSchema),
  /** Frame where the voiceover Audio sequence starts (word timing anchor). */
  voStartFrame: z.number().int().min(0),
  /** Caption centerline within the safe zone (0 top … 1 bottom); ~0.55–0.62. */
  captionVertical: z.number().min(0).max(1),
  /** @deprecated One motion per moment (2026-07-13) — leave []; kept for legacy props. */
  punchIns: z.array(punchInSchema),
  /** White luma-flash transitions — peak opacity ON these frames (4–6f total). */
  flashFrames: z.array(z.number().int().min(0)),
  /** Color pops: desaturated 45f hold → snap to full color ON each frame. */
  colorPops: z.array(z.number().int().min(0)).default([]),
  /** Impact shakes: 10f decaying translate jitter at each frame (boom moments). */
  screenShakes: z.array(z.object({ frame: z.number().int().min(0), intensity: z.number().min(0).max(1) })).default([]),
  /** SFX cues (whoosh/riser/boom/click — see the skill's SFX grammar). */
  sfx: z.array(sfxSchema),
  voiceoverSrc: z.string().nullable(),
  musicSrc: z.string().nullable(),
  /** Small icon-logo watermark, top-right in the safe zone (null = off). */
  watermarkSrc: z.string().nullable(),
  /** Watermark width in px (also the logo-dock landing width). */
  watermarkWidth: z.number().positive().default(110),
  /** Opening logo entrance→dock; null = no logo intro (end card only). */
  logoIntro: logoIntroSchema.nullable().default(null),
  /** @deprecated One motion per moment (2026-07-13) — leave []; kept for legacy props. */
  zoomOutReveals: z.array(z.number().int().min(0)).default([]),
  /**
   * Dark scrim behind the hook title + logo intro so cold-open text reads
   * over bright footage. Peak opacity; fades in over the first 8f, out over
   * 12f after the hook exits. 0 = off.
   */
  hookScrimOpacity: z.number().min(0).max(1).default(0),
  /**
   * Branded info block filling the space UNDER a framed card (logo lockup +
   * two lines, staggered entrance). Anchored to clips[brandClipIndex].
   */
  brandBlock: z
    .object({ logoSrc: z.string(), line1: z.string(), line2: z.string() })
    .nullable()
    .default(null),
  brandClipIndex: z.number().int().nullable().default(null),
  /**
   * Camera-snap photo montage over clips[clipIndex]: each photo enters
   * full-bleed at its absolute frame with a shutter-pop settle (pair each
   * frame with a shutter SFX cue). Later photos stack on top.
   */
  photoBurst: z
    .object({
      clipIndex: z.number().int(),
      photos: z.array(z.object({ src: z.string(), frame: z.number().int().min(0) })),
      /** Burst treatment — full-bleed snaps (house v5), polaroid scatter, or 2×2 grid assemble. */
      style: z.enum(['fullbleed', 'polaroid-scatter', 'grid']).default('fullbleed'),
    })
    .nullable()
    .default(null),
  /** Music bed level while the voiceover talks (ducked); ~0.15–0.25. */
  musicVolume: z.number().min(0).max(1),
  endCard: z.object({
    headline: z.string(),
    sub: z.string(),
    cta: z.string(),
  }),
  endCardFrames: z.number().int().positive(),
})

export type ShowcaseReelProps = z.infer<typeof showcaseReelSchema>
export type Caption = z.infer<typeof captionSchema>
export type Clip = z.infer<typeof clipSchema>
