import { z } from 'zod'

export const clipSchema = z.object({
  /** Filename under video/public/ (Remotion staticFile). */
  src: z.string(),
  /** `video` plays the file; `image` shows a still with a slow Ken Burns push. */
  kind: z.enum(['video', 'image']),
  durationInFrames: z.number().int().positive(),
  /**
   * `full` = full-bleed cover (needs a true 9:16 source clip).
   * `framed` = editorial card on the dark brand ground — native aspect, no
   * quality-destroying crop; use for landscape clips.
   */
  layout: z.enum(['full', 'framed']),
  /** Width/height of the source clip — sizes the framed card. */
  aspect: z.number().positive(),
  /** Uppercase chip above a framed card (e.g. "THE SHOWCASE STANDARD"). */
  label: z.string().nullable(),
  /** Ken Burns direction for `kind: 'image'`: slow push in, or settle out. */
  kenBurns: z.enum(['in', 'out']).default('in'),
})

export const captionSchema = z.object({
  /** `*word*` marks the emphasis word (brand blue + scale); max one per line. */
  text: z.string(),
  startFrame: z.number().int().min(0),
  endFrame: z.number().int().min(1),
})

/** Punch-in: hard 1-frame scale jump on the clips layer, decaying back over ~10f. */
export const punchInSchema = z.object({
  frame: z.number().int().min(0),
  /** 1.10–1.15 hard, ≤1.20 (digital zoom quality ceiling). */
  scale: z.number().min(1).max(1.2),
})

/** SFX cue — transient must land ON the visual hit frame (editing-patterns.md). */
export const sfxSchema = z.object({
  src: z.string(),
  frame: z.number().int().min(0),
  volume: z.number().min(0).max(1),
})

/**
 * Opening brand moment: lockup springs in centered over the cold-open shot,
 * then glides in one continuous motion into the watermark slot, where the
 * persistent watermark takes over on the landing frame (dockFrame + 15).
 */
export const logoIntroSchema = z.object({
  /** Full lockup art — use the same file as watermarkSrc for a seamless dock. */
  src: z.string(),
  enterFrame: z.number().int().min(0),
  dockFrame: z.number().int().min(0),
})

/** Word caption (@remotion/captions shape) — generated by scripts/transcribe.mjs. */
export const wordCaptionSchema = z.object({
  text: z.string(),
  startMs: z.number(),
  endMs: z.number(),
  timestampMs: z.number().nullable(),
  confidence: z.number().nullable(),
})

export const showcaseReelSchema = z.object({
  clips: z.array(clipSchema).min(1),
  /** Kinetic hook headline; shows hookStartFrame → hookStartFrame + hookDurationInFrames. */
  hook: z.string(),
  hookStartFrame: z.number().int().min(0).default(0),
  hookDurationInFrames: z.number().int().positive().default(75),
  /** Checkmark rows shown above the framed card of clips[checkmarkClipIndex]. */
  checkmarks: z.array(z.string()).max(4),
  checkmarkClipIndex: z.number().int().nullable(),
  /** Burned-in captions mirroring the voiceover (most viewers watch muted). */
  captions: z.array(captionSchema),
  /**
   * Word-level captions (whisper-timed via scripts/transcribe.mjs). When
   * non-empty they REPLACE `captions` with CapCut-style karaoke pages —
   * timing comes from the audio itself, so drift is impossible.
   */
  wordCaptions: z.array(wordCaptionSchema),
  /** Frame where the voiceover Audio sequence starts (word timing anchor). */
  voStartFrame: z.number().int().min(0),
  /** Caption centerline within the safe zone (0 top … 1 bottom); ~0.55–0.62. */
  captionVertical: z.number().min(0).max(1),
  /** Punch zooms on stressed VO words / downbeats. */
  punchIns: z.array(punchInSchema),
  /** White luma-flash transitions — peak opacity ON these frames (4–6f total). */
  flashFrames: z.array(z.number().int().min(0)),
  /** SFX cues (whoosh/riser/boom/click — see the skill's SFX grammar). */
  sfx: z.array(sfxSchema),
  voiceoverSrc: z.string().nullable(),
  musicSrc: z.string().nullable(),
  /** Small icon-logo watermark, top-right in the safe zone (null = off). */
  watermarkSrc: z.string().nullable(),
  /** Watermark width in px (also the logo-dock landing width). */
  watermarkWidth: z.number().positive().default(110),
  /** Opening logo entrance→dock; null = no logo intro (end card only). */
  logoIntro: logoIntroSchema.nullable().default(null),
  /** Zoom-out reveals: 150→100% over 10f starting at each frame (after-shot arrivals). */
  zoomOutReveals: z.array(z.number().int().min(0)).default([]),
  /** Music bed level while the voiceover talks (ducked); ~0.15–0.25. */
  musicVolume: z.number().min(0).max(1),
  endCard: z.object({
    headline: z.string(),
    sub: z.string(),
    cta: z.string(),
  }),
  endCardFrames: z.number().int().positive(),
})

export type ShowcaseReelProps = z.infer<typeof showcaseReelSchema>
export type Caption = z.infer<typeof captionSchema>
export type Clip = z.infer<typeof clipSchema>
