export const dashboardSteps = [
  'customer-pipelines',
  'meetings',
  'edit-meeting',
  'proposals',
  'create-proposal',
  'edit-proposal',
  'showroom',
  'create-project',
  'edit-project',
  'dashboard',
  'settings',
  'intake',
  'team',
  'analytics',
] as const
