// Generated by scripts/generate-pwa-splash.ts; run it again instead of editing.
export const PWA_STARTUP_IMAGE_VERSION = 'v3'

/** One entry per device and orientation for appleWebApp.startupImage. */
export const PWA_STARTUP_IMAGES: { url: string, media: string }[] = [
  {
    url: '/pwa/splash/apple-splash-640-1136-v3.png',
    media: 'screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-1136-640-v3.png',
    media: 'screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-750-1334-v3.png',
    media: 'screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-1334-750-v3.png',
    media: 'screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1242-2208-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2208-1242-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1125-2436-v3.png',
    media: 'screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2436-1125-v3.png',
    media: 'screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-828-1792-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-1792-828-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1242-2688-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2688-1242-v3.png',
    media: 'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1170-2532-v3.png',
    media: 'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2532-1170-v3.png',
    media: 'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1284-2778-v3.png',
    media: 'screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2778-1284-v3.png',
    media: 'screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1179-2556-v3.png',
    media: 'screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2556-1179-v3.png',
    media: 'screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1290-2796-v3.png',
    media: 'screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2796-1290-v3.png',
    media: 'screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1206-2622-v3.png',
    media: 'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2622-1206-v3.png',
    media: 'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1320-2868-v3.png',
    media: 'screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2868-1320-v3.png',
    media: 'screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1260-2736-v3.png',
    media: 'screen and (device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2736-1260-v3.png',
    media: 'screen and (device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1488-2266-v3.png',
    media: 'screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2266-1488-v3.png',
    media: 'screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1536-2048-v3.png',
    media: 'screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2048-1536-v3.png',
    media: 'screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1620-2160-v3.png',
    media: 'screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2160-1620-v3.png',
    media: 'screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1640-2360-v3.png',
    media: 'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2360-1640-v3.png',
    media: 'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1668-2224-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2224-1668-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1668-2388-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2388-1668-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-1668-2420-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2420-1668-v3.png',
    media: 'screen and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-2048-2732-v3.png',
    media: 'screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2732-2048-v3.png',
    media: 'screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
  {
    url: '/pwa/splash/apple-splash-2064-2752-v3.png',
    media: 'screen and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
  },
  {
    url: '/pwa/splash/apple-splash-2752-2064-v3.png',
    media: 'screen and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)',
  },
]

/** The logical portrait sizes the matrix covers; the device probe checks a phone against them. */
export const PWA_STARTUP_IMAGE_SIZES: { width: number, height: number, scale: number }[] = [
  {
    width: 320,
    height: 568,
    scale: 2,
  },
  {
    width: 375,
    height: 667,
    scale: 2,
  },
  {
    width: 414,
    height: 736,
    scale: 3,
  },
  {
    width: 375,
    height: 812,
    scale: 3,
  },
  {
    width: 414,
    height: 896,
    scale: 2,
  },
  {
    width: 414,
    height: 896,
    scale: 3,
  },
  {
    width: 390,
    height: 844,
    scale: 3,
  },
  {
    width: 428,
    height: 926,
    scale: 3,
  },
  {
    width: 393,
    height: 852,
    scale: 3,
  },
  {
    width: 430,
    height: 932,
    scale: 3,
  },
  {
    width: 402,
    height: 874,
    scale: 3,
  },
  {
    width: 440,
    height: 956,
    scale: 3,
  },
  {
    width: 420,
    height: 912,
    scale: 3,
  },
  {
    width: 744,
    height: 1133,
    scale: 2,
  },
  {
    width: 768,
    height: 1024,
    scale: 2,
  },
  {
    width: 810,
    height: 1080,
    scale: 2,
  },
  {
    width: 820,
    height: 1180,
    scale: 2,
  },
  {
    width: 834,
    height: 1112,
    scale: 2,
  },
  {
    width: 834,
    height: 1194,
    scale: 2,
  },
  {
    width: 834,
    height: 1210,
    scale: 2,
  },
  {
    width: 1024,
    height: 1366,
    scale: 2,
  },
  {
    width: 1032,
    height: 1376,
    scale: 2,
  },
]
