export const PRICING_KEYS = [
  'overlay',
  'tearOff',
  'redeck',
  'tileReset',
  'installPanels',
  'rnrPanels',
  'installBattery',
  'replaceSplitSystem',
  'replaceFurnace',
  'installMiniSplit',
  'replaceWindows',
  'replaceSlidingDoor',
  'replaceFrenchDoors',
  'rnrAttic',
  'topOffAttic',
  'installCrawlSpaceInsulation',
  'installArtificial',
  'installGravel',
  'installMulch',
  'installConcrete',
  'installPavers',
  'installDg',
  'mpu',
  'installExteriorPaint',
] as const

export type PricingKey = typeof PRICING_KEYS[number]
