import z from 'zod'

import { getFinanceOptions } from '@/shared/entities/finance-options/dal/server/queries'
import { proposalCreateDal, proposalDuplicateDal } from '@/shared/entities/proposals/dal/server/mutations'
import { getFullView, listProposals, proposalListInputSchema } from '@/shared/entities/proposals/dal/server/queries'
import { proposalSchemas, proposalServerSpec } from '@/shared/entities/proposals/lib/server-spec'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { dalToTrpc } from '../../lib/dal-to-trpc'
import { createContractsRouter } from './contracts.router'
import { createDeliveryRouter } from './delivery.router'

export const proposalsRouter = createEntityRouter(proposalServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter — wires CASL gating, Zod validation,
    // shareable procedure selection, and dalToTrpc bridge automatically.
    // Custom handlers override create (kind derivation + token gen + SOW
    // snapshot) and duplicate (cherry-pick + owner reassignment + status reset).
    crud: createCrudRouter({
      spec: proposalServerSpec,
      schemas: { ...proposalSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
      handlers: { create: proposalCreateDal, duplicate: proposalDuplicateDal },
    }),

    // ── Business queries ──────────────────────────────────────────────────
    // Enriched reads and complex list with entity-specific joins/filters.
    // These use free-form return types — not Row<TTable>.
    business: createTRPCRouter({
      getFullView: entity.shareableProcedure
        .input(z.object({ id: z.string().uuid(), token: z.string().optional() }))
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await getFullView(ctx, input)) ?? null
        }),

      list: entity.authedProcedure
        .input(proposalListInputSchema)
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await listProposals(ctx, input))
        }),

      getFinanceOptions: entity.publicProcedure
        .query(async () => {
          return getFinanceOptions()
        }),
    }),

    // ── Service-layer sub-routers ─────────────────────────────────────────
    delivery: createDeliveryRouter(entity),
    contracts: createContractsRouter(entity),
  })
})
