import { TRPCError } from '@trpc/server'
import z from 'zod'

import { getFinanceOptions } from '@/shared/entities/finance-options/dal/server/queries'
import { replaceProposalIncentives } from '@/shared/entities/proposals/dal/server/mutations'
import { getFullView, listProposals, proposalListInputSchema } from '@/shared/entities/proposals/dal/server/queries'
import { proposalSchemas, proposalServerSpec } from '@/shared/entities/proposals/lib/server-spec'
import { incentiveSchema } from '@/shared/entities/proposals/schemas'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { dalToTrpc } from '../../lib/dal-to-trpc'
import { createContractsRouter } from './contracts.router'
import { createDeliveryRouter } from './delivery.router'

export const proposalsRouter = createEntityRouter(proposalServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter. Create enrichment (kind derivation,
    // token gen, SOW snapshot) and duplicate config (field exclusion, status
    // reset) now live on proposalServerSpec.hooks and .duplicate.
    crud: createCrudRouter({
      spec: proposalServerSpec,
      schemas: { ...proposalSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
    }),

    // ── Business queries ──────────────────────────────────────────────────
    // Enriched reads and complex list with entity-specific joins/filters.
    // These use free-form return types — not Row<TTable>.
    business: createTRPCRouter({
      getFullView: entity.shareableProcedure
        .input(z.object({ id: z.string().uuid(), token: z.string().optional() }))
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await getFullView(ctx, input)) ?? null
        }),

      list: entity.authedProcedure
        .input(proposalListInputSchema)
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await listProposals(ctx, input))
        }),

      getFinanceOptions: entity.publicProcedure
        .query(async () => {
          return getFinanceOptions()
        }),
    }),

    // ── Incentives (proposal_incentives child rows, Wave 2) ─────────────
    // Replace-all upsert from the funding form. Freeze gate (signingRequestId)
    // enforced in the DAL. see ../../../shared/entities/proposals/DOCS.md#final-tcp-derived
    incentives: createTRPCRouter({
      replace: entity.authedProcedure
        .input(z.object({
          proposalId: z.string().uuid(),
          incentives: z.array(incentiveSchema),
        }))
        .mutation(async ({ ctx, input }) => {
          if (ctx.ability.cannot('update', 'Proposal')) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'You do not have permission to update this proposal.',
            })
          }
          return dalToTrpc(await replaceProposalIncentives(ctx, input))
        }),
    }),

    // ── Service-layer sub-routers ─────────────────────────────────────────
    delivery: createDeliveryRouter(entity),
    contracts: createContractsRouter(entity),
  })
})
