import { TRPCError } from '@trpc/server'
import z from 'zod'

import { getFinanceOptions } from '@/shared/entities/finance-options/dal/server/queries'
import { duplicateProposalWithIncentives } from '@/shared/entities/proposals/dal/server/duplicate'
import { replaceProposalIncentives, setCashInDeal } from '@/shared/entities/proposals/dal/server/mutations'
import { getFullView, listProposals, proposalListInputSchema } from '@/shared/entities/proposals/dal/server/queries'
import { proposalSchemas, proposalServerSpec } from '@/shared/entities/proposals/lib/server-spec'
import { incentiveSchema } from '@/shared/entities/proposals/schemas'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { dalToTrpc } from '../../lib/dal-to-trpc'
import { createContractsRouter } from './contracts.router'
import { createDeliveryRouter } from './delivery.router'
import { createProposalMediaRouter } from './media.router'

export const proposalsRouter = createEntityRouter(proposalServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter. Create enrichment (kind derivation,
    // token gen, SOW snapshot) and duplicate config (field exclusion, status
    // reset) now live on proposalServerSpec.hooks and .duplicate.
    //
    // crud.duplicate is overridden — the generic duplicateImpl only copies
    // the parent row, never `proposal_incentives` (a Wave-2 child table),
    // which would silently drop discounts/exclusive-offers on the copy. see
    // ../../../shared/entities/proposals/DOCS.md#duplicate-resets-and-redrives
    crud: createCrudRouter({
      spec: proposalServerSpec,
      schemas: { ...proposalSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
      handlers: {
        duplicate: duplicateProposalWithIncentives,
      },
    }),

    // ── Business queries ──────────────────────────────────────────────────
    // Enriched reads and complex list with entity-specific joins/filters.
    // These use free-form return types — not Row<TTable>.
    business: createTRPCRouter({
      getFullView: entity.shareableProcedure
        .input(z.object({ id: z.string().uuid(), token: z.string().optional() }))
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await getFullView(ctx, input)) ?? null
        }),

      list: entity.authedProcedure
        .input(proposalListInputSchema)
        .query(async ({ ctx, input }) => {
          return dalToTrpc(await listProposals(ctx, input))
        }),

      getFinanceOptions: entity.publicProcedure
        .query(async () => {
          return getFinanceOptions()
        }),
    }),

    // ── Incentives (proposal_incentives child rows, Wave 2) ─────────────
    // Replace-all upsert from the funding form. Freeze gate (contractEnvelopeId)
    // enforced in the DAL. see ../../../shared/entities/proposals/DOCS.md#final-tcp-derived
    incentives: createTRPCRouter({
      replace: entity.authedProcedure
        .input(z.object({
          proposalId: z.string().uuid(),
          incentives: z.array(incentiveSchema),
        }))
        .mutation(async ({ ctx, input }) => {
          if (ctx.ability.cannot('update', 'Proposal')) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'You do not have permission to update this proposal.',
            })
          }
          return dalToTrpc(await replaceProposalIncentives(ctx, input))
        }),
    }),

    // ── Funding (narrow blob-scalar writes) ─────────────────────────────
    // Each funding scalar gets its own narrow mutation instead of a
    // client-side whole-blob reconstruction (seam register ruling
    // 2026-07-16). W3 turns these into plain column writes.
    funding: createTRPCRouter({
      setCashInDeal: entity.shareableProcedure
        .input(z.object({
          id: z.string().uuid(),
          token: z.string().optional(),
          cashInDeal: z.number().min(0),
        }))
        .mutation(async ({ ctx, input }) => {
          return dalToTrpc(await setCashInDeal(ctx, { proposalId: input.id, cashInDeal: input.cashInDeal }))
        }),
    }),

    // ── Service-layer sub-routers ─────────────────────────────────────────
    delivery: createDeliveryRouter(entity),
    contracts: createContractsRouter(entity),
    media: createProposalMediaRouter(entity),
  })
})
