export const tradeOutcomeStatements: Record<string, string> = {
  'hvac': 'Your system will use roughly half the energy of your current unit — and you\'ll be able to control it from your phone.',
  'roof-and-gutters': 'Your home will be fully protected from weather damage for the next 30 years — no more worrying about the next storm.',
  'windows-and-doors': 'No more drafts, no more noise from outside, and your home stays at a consistent temperature without your HVAC working overtime.',
  'attic-and-basement': 'You\'ll notice the comfort difference almost immediately — and most customers see their heating and cooling bills drop by 20–40%.',
  'solar': 'You\'re locking in your energy rate for 25 years while your neighbors keep paying whatever the utility charges.',
  'exterior-paint-stucco-and-siding': 'A refreshed exterior that protects your home from the elements and dramatically improves curb appeal.',
  'water-heating': 'Endless hot water on demand, with a unit that takes up a fraction of the space and uses significantly less energy.',
  'dryscaping': 'A beautiful, low-maintenance landscape that conserves water and enhances your outdoor living space.',
  'kitchen-remodel': 'A completely updated kitchen — dramatically improved functionality and the highest ROI of any home improvement.',
  'bathroom-remodel': 'A bathroom you\'ll love using every day — like moving into a new house, without moving.',
  'flooring': 'Updated aesthetics throughout your home with improved durability and ease of maintenance.',
  'addition': 'More space for your family without the cost and disruption of moving to a new home.',
  'exterior-upgrades-and-lot-layout': 'Expanded outdoor living space that increases your home value and daily enjoyment.',
  'interior-upgrades-and-home-layout': 'A modernized interior that transforms how your home looks and feels.',
  'patch-and-interior-paint': 'A refreshed, modernized appearance — high perceived value for relatively low investment.',
  'tile': 'Beautiful, durable tile work that elevates any space in your home.',
  'pool-remodel': 'A restored pool that becomes the centerpiece of your backyard again.',
  'adu': 'A complete accessory dwelling unit — from permits to finished space, handled by one team.',
  'fencing-and-gates': 'Enhanced privacy, security, and curb appeal for your property.',
  'garage': 'A functional, well-built garage that protects your vehicles and adds usable space.',
  'electricals': 'A modern, safe electrical system that supports your home\'s current and future needs.',
  'plumbing': 'Reliable plumbing that eliminates leaks, low pressure, and aging pipe concerns.',
  'foundation-and-crawl-space': 'Your home will be structurally stable, and when you go to sell it, it will pass inspection without any issues.',
  'hazardous-materials': 'A safe, clean home free from hidden health hazards — documented and certified.',
  'framing': 'Solid structural framing that forms the backbone of any construction project.',
  'engineering-plans-and-blueprints': 'Professional plans and blueprints that ensure your project is built to code from day one.',
}
