// src/features/landing/constants/trade-pain-headlines.ts
// Sparse lookup — not all possible slugs are listed, fallback handled at call site.
export const tradePainHeadlines: Partial<Record<string, string>> = {
  'hvac': 'Your home shouldn\'t be this expensive to keep comfortable.',
  'roof-and-gutters': 'Your roof is the one thing between your home and the next storm.',
  'windows-and-doors': 'Your windows are working against your home — not for it.',
  'attic-and-basement': 'Your home is leaking energy — and your bills prove it.',
  'solar': 'You\'re renting energy from your utility company. You don\'t have to.',
  'exterior-paint-stucco-and-siding': 'Your home\'s exterior is its first impression — and its first line of defense.',
  'water-heating': 'Heating water you didn\'t use, waiting for hot water you can\'t get fast enough.',
  'dryscaping': 'Your lot should work as hard as the rest of your home.',
  'kitchen-remodel': 'A kitchen that wasn\'t designed for how you actually live.',
  'bathroom-remodel': 'A bathroom you deserve to love — not just tolerate.',
  'flooring': 'Flooring that\'s seen better days changes how every room feels.',
  'addition': 'Your family has outgrown your home. The answer might not be moving.',
  'exterior-upgrades-and-lot-layout': 'Your outdoor space is wasted potential.',
  'interior-upgrades-and-home-layout': 'Your home\'s layout shouldn\'t feel like a compromise.',
  'patch-and-interior-paint': 'Fresh paint changes everything. Yours is overdue.',
  'tile': 'Old tile doesn\'t just look dated — it changes how a room feels to live in.',
  'pool-remodel': 'A pool should be an asset, not an eyesore.',
  'adu': 'You have untapped value sitting in your garage or backyard.',
  'fencing-and-gates': 'Privacy, security, and curb appeal start at the property line.',
  'garage': 'Your garage is doing more work than it should have to.',
  'electricals': 'Your home\'s electrical system should be invisible when it works — and safe when it\'s tested.',
  'plumbing': 'Old pipes don\'t announce themselves until they fail.',
  'foundation-and-crawl-space': 'Your foundation is doing its job quietly — until it isn\'t.',
  'hazardous-materials': 'Asbestos, mold, and termites don\'t wait.',
  'engineering-plans-and-blueprints': 'A great build starts with a great plan.',
}
