import { and, eq, ne } from 'drizzle-orm'

import { createCrudDal } from '@/shared/dal/server/lib/create-crud-dal'
import { dalVerifySuccess } from '@/shared/dal/server/lib/helpers'
import { SYSTEM_CONTEXT, ThrowableDalError } from '@/shared/dal/server/types'
import { db } from '@/shared/db'
import { customers } from '@/shared/db/schema/customers'
import { leadSourcesTable } from '@/shared/db/schema/lead-sources'
import { leadSourceServerSpec } from '@/shared/entities/lead-sources/lib/server-spec'
import { generateToken } from '@/shared/lib/generate-token'
import { slugify } from '@/shared/lib/slugify'

/**
 * Bespoke in-DAL helper (§5.9): generate a slug unique against existing rows,
 * appending -2, -3, … on collision. Moved verbatim from the old hand-rolled
 * router. Precondition-fails after 50 attempts (effectively unreachable).
 */
async function generateUniqueSlug(base: string): Promise<string> {
  const root = slugify(base, { maxLen: 64 }) || 'source'
  for (let i = 0; i < 50; i++) {
    const candidate = i === 0 ? root : `${root}-${i + 1}`
    const [existing] = await db
      .select({ id: leadSourcesTable.id })
      .from(leadSourcesTable)
      .where(eq(leadSourcesTable.slug, candidate))
      .limit(1)
    if (!existing) {
      return candidate
    }
  }
  throw new ThrowableDalError({ type: 'precondition-failed', reason: 'Could not generate a unique slug.' })
}

/**
 * Stable CRUD handlers for the lead-sources entity. All lifecycle business
 * logic lives here (config factory), not on the spec. Super-admin-only:
 * callers route through `superAdminProcedure` (omni, `scope: null`).
 */
export const leadSourceCrud = createCrudDal(leadSourceServerSpec, crudHandlers => ({
  hooks: {
    create: {
      // Router previously derived slug/token/isActive from { name, formConfigJSON }.
      // Always generate a fresh unique slug + token (the create surface never
      // accepted a client-supplied slug). isActive flows through untouched:
      // absent on a direct create → DB default (true); the duplicate path's
      // override sets it false before this hook runs, so don't force it here.
      async before(input) {
        return { ...input, slug: await generateUniqueSlug(input.name), token: generateToken() }
      },
    },
    update: {
      // Token rotates ONLY when the slug actually changes — a no-op save (the
      // UI echoes the existing slug) must not rotate live intake URLs. Reject
      // malformed slugs and duplicates against any OTHER source. Own-entity
      // read via the crudHandlers factory arg.
      async before(data, _ctx, { id }) {
        if (data.slug === undefined) {
          return data
        }
        if (slugify(data.slug, { maxLen: 64 }) !== data.slug) {
          throw new ThrowableDalError({
            type: 'precondition-failed',
            reason: 'Use lowercase letters, numbers, and hyphens only.',
          })
        }
        const current = dalVerifySuccess(await crudHandlers.getById(SYSTEM_CONTEXT, { id: String(id) }))
        if (!current) {
          throw new ThrowableDalError({ type: 'not-found' })
        }
        if (data.slug === current.slug) {
          return data // no-op → no token rotation
        }
        const [dupe] = await db
          .select({ id: leadSourcesTable.id })
          .from(leadSourcesTable)
          .where(and(eq(leadSourcesTable.slug, data.slug), ne(leadSourcesTable.id, String(id))))
          .limit(1)
        if (dupe) {
          throw new ThrowableDalError({ type: 'precondition-failed', reason: 'That slug is already in use.' })
        }
        return { ...data, token: generateToken() }
      },
    },
    delete: {
      // Attached-customer precondition (G4: engine hands us the row). Reason is
      // surfaced verbatim to the client toast via dalToTrpc (PRECONDITION_FAILED).
      async before(row) {
        const attached = await db.$count(customers, eq(customers.leadSourceId, row.id))
        if (attached > 0) {
          throw new ThrowableDalError({
            type: 'precondition-failed',
            reason: `${attached} ${attached === 1 ? 'customer is' : 'customers are'} still attached. Reassign or archive instead.`,
          })
        }
      },
    },
  },
  // Duplicate copies ONLY name (via override) + formConfigJSON; slug/token are
  // regenerated by create.before (routed through createImpl), isActive forced
  // false. The voip-campaign columns are excluded to reset dial config to
  // defaults — exact parity with the pre-standardization hand-rolled duplicate,
  // which predates those columns and never copied them.
  duplicate: {
    exclude: [
      'createdAt',
      'updatedAt',
      'slug',
      'token',
      'archivedAt',
      'voipCampaignsEnabled',
      'voipAutoEnroll',
      'defaultCampaignId',
      'dailyDialVolumeCap',
      'messageTemplateOverridesJSON',
      'voipInHouseConfigJSON',
    ],
    overrides: source => ({ name: `${source.name} (copy)`, isActive: false }),
  },
}))
