import { readFileSync, writeFileSync } from 'node:fs'

// One-time generator for the Tri Pros service-area ZIP set. Reads a ZIP→county
// crosswalk at scripts/data/uszips.csv (gitignored build input, columns:
// zip,state_id,county_name) and emits src/shared/constants/company/service-area-zips.ts.
// Re-run after editing the rules below. Pure file IO — no env, no network, no deps.

// WHOLE-COUNTY inclusions. Only LA, Orange, and Ventura are taken whole (LA incl.
// the Antelope Valley up to Rosamond). San Bernardino and Riverside are NOT whole —
// their counties run far east into the desert/mountains we don't serve, so they are
// included by an explicit western-city ZIP list instead (see below).
const WHOLE_COUNTIES = new Set(['Los Angeles', 'Orange', 'Ventura'])

// Curated edge trims for the whole counties (boundary cities the user defined).
//  - Orange County south of Laguna Beach: San Clemente, Dana Point, San Juan Capistrano.
//  - Ventura County far-north/rural beyond the city of Ventura: Ojai, Santa Paula, Fillmore, Piru.
const EXCLUDE = new Set([
  '92672',
  '92673',
  '92674', // San Clemente
  '92624',
  '92629', // Dana Point
  '92675',
  '92690',
  '92693', // San Juan Capistrano
  '93023',
  '93024', // Ojai
  '93060',
  '93061', // Santa Paula
  '93015',
  '93016', // Fillmore
  '93040', // Piru
])

// San Bernardino County — western strip only (LA line east through Fontana; nothing
// past Fontana, no High Desert / Mojave / mountains). Explicit ZIPs by city.
const SAN_BERNARDINO_INCLUDED = new Set([
  '91709', // Chino Hills
  '91708',
  '91710', // Chino
  '91763', // Montclair
  '91758',
  '91761',
  '91762',
  '91764',
  '91798', // Ontario
  '91784',
  '91785',
  '91786', // Upland
  '91701',
  '91729',
  '91730',
  '91737',
  '91739', // Rancho Cucamonga
  '92331',
  '92334',
  '92335',
  '92336',
  '92337', // Fontana
])

// Riverside County — only the western sliver pressed against the LA/Orange corner.
const RIVERSIDE_INCLUDED = new Set([
  '92877',
  '92878',
  '92879',
  '92880',
  '92881',
  '92882',
  '92883', // Corona (incl. Eastvale 92880)
  '92860', // Norco
  '91752', // Mira Loma
])

// Explicit extra inclusions outside the whole counties.
const EXTRA = new Set(['93560']) // Rosamond (Kern) — north sliver

// Minimal CSV read — the normalized crosswalk has no quoted/embedded-comma
// fields, so a plain split is sufficient (avoids a csv-parse dependency).
const lines = readFileSync('scripts/data/uszips.csv', 'utf8').trim().split('\n')
const header = lines[0].split(',')
const col = {
  zip: header.indexOf('zip'),
  state_id: header.indexOf('state_id'),
  county_name: header.indexOf('county_name'),
}
const rows = lines.slice(1).map((line) => {
  const c = line.split(',')
  return { zip: c[col.zip], state_id: c[col.state_id], county_name: c[col.county_name] }
})

const zips = new Set<string>()
for (const r of rows) {
  const zip = r.zip.padStart(5, '0')
  if (r.state_id !== 'CA') {
    continue
  }
  if (WHOLE_COUNTIES.has(r.county_name) && !EXCLUDE.has(zip)) {
    zips.add(zip)
  }
}
for (const z of SAN_BERNARDINO_INCLUDED) {
  zips.add(z)
}
for (const z of RIVERSIDE_INCLUDED) {
  zips.add(z)
}
for (const z of EXTRA) {
  zips.add(z)
}

const sorted = [...zips].sort()
const body = `// GENERATED by scripts/generate-service-area-zips.ts — do not edit by hand.\n`
  + `// Tri Pros service area: LA whole (incl. Antelope Valley), Orange north of Laguna,\n`
  + `// Ventura up to Ventura city, the western San Bernardino strip (Chino Hills→Fontana),\n`
  + `// the western Riverside sliver (Corona/Norco/Mira Loma), plus Rosamond. ${sorted.length} ZIPs.\n`
  + `export const SERVICE_AREA_ZIPS: ReadonlySet<string> = new Set([\n${
    sorted.map(z => `  '${z}',`).join('\n')
  }\n])\n`

writeFileSync('src/shared/constants/company/service-area-zips.ts', body)
console.log(`Wrote ${sorted.length} ZIPs to service-area-zips.ts`)
