/* eslint-disable no-console */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import { PWA_LAUNCH_FIELD } from '@/shared/domains/pwa/constants/launch'

// Run: pnpm exec tsx scripts/generate-pwa-splash.ts && CI=1 npx eslint --fix src/shared/domains/pwa/constants/startup-images.ts
//
// iOS paints a startup image only when one entry's media query matches the device exactly, and it keys its
// cache on the file URL: bump VERSION whenever the picture changes, or a re-added app keeps the old one.
const VERSION = 'v3'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const OUT_DIR = resolve(ROOT, 'public/pwa/splash')
const CONSTANTS_PATH = resolve(ROOT, 'src/shared/domains/pwa/constants/startup-images.ts')
const LOGO_SVG = resolve(ROOT, 'public/company/logo/logo-dark.svg')
const PUBLIC_PREFIX = '/pwa/splash'

interface Device {
  /** Logical portrait size in CSS points; iOS reports these in both orientations. */
  width: number
  height: number
  scale: number
  name: string
}

const DEVICES: Device[] = [
  { width: 320, height: 568, scale: 2, name: 'iPhone SE (1st), 5s' },
  { width: 375, height: 667, scale: 2, name: 'iPhone 6–8, SE (2nd, 3rd)' },
  { width: 414, height: 736, scale: 3, name: 'iPhone 6–8 Plus' },
  { width: 375, height: 812, scale: 3, name: 'iPhone X, XS, 11 Pro, 12 mini, 13 mini' },
  { width: 414, height: 896, scale: 2, name: 'iPhone XR, 11' },
  { width: 414, height: 896, scale: 3, name: 'iPhone XS Max, 11 Pro Max' },
  { width: 390, height: 844, scale: 3, name: 'iPhone 12, 12 Pro, 13, 13 Pro, 14, 16e' },
  { width: 428, height: 926, scale: 3, name: 'iPhone 12 Pro Max, 13 Pro Max, 14 Plus' },
  { width: 393, height: 852, scale: 3, name: 'iPhone 14 Pro, 15, 15 Pro, 16' },
  { width: 430, height: 932, scale: 3, name: 'iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus' },
  { width: 402, height: 874, scale: 3, name: 'iPhone 16 Pro, 17, 17 Pro' },
  { width: 440, height: 956, scale: 3, name: 'iPhone 16 Pro Max, 17 Pro Max' },
  { width: 420, height: 912, scale: 3, name: 'iPhone Air' },
  { width: 744, height: 1133, scale: 2, name: 'iPad mini (6th, 7th)' },
  { width: 768, height: 1024, scale: 2, name: 'iPad 9.7", mini 5, Air 2' },
  { width: 810, height: 1080, scale: 2, name: 'iPad 10.2"' },
  { width: 820, height: 1180, scale: 2, name: 'iPad 10.9" (10th, 11th), Air 10.9"/11"' },
  { width: 834, height: 1112, scale: 2, name: 'iPad Pro 10.5", Air 3' },
  { width: 834, height: 1194, scale: 2, name: 'iPad Pro 11" (1st–4th)' },
  { width: 834, height: 1210, scale: 2, name: 'iPad Pro 11" (M4, M5)' },
  { width: 1024, height: 1366, scale: 2, name: 'iPad Pro 12.9", Air 13"' },
  { width: 1032, height: 1376, scale: 2, name: 'iPad Pro 13" (M4, M5)' },
]

const ORIENTATIONS = ['portrait', 'landscape'] as const

// The cover renders the mark 192 CSS px wide under a 640 px viewport and 224 px from there (w-48 sm:w-56);
// the image shows the same mark at the same size, so the handoff from the image to the cover moves nothing.
function markCssWidth(viewportCssWidth: number): number {
  return viewportCssWidth < 640 ? 192 : 224
}

mkdirSync(OUT_DIR, { recursive: true })
for (const existing of readdirSync(OUT_DIR)) {
  if (existing.startsWith('apple-splash-') && existing.endsWith('.png')) {
    rmSync(resolve(OUT_DIR, existing))
  }
}

const svg = readFileSync(LOGO_SVG)
const entries: { url: string, media: string }[] = []
const written = new Set<string>()

for (const device of DEVICES) {
  for (const orientation of ORIENTATIONS) {
    const cssW = orientation === 'portrait' ? device.width : device.height
    const cssH = orientation === 'portrait' ? device.height : device.width
    const pxW = cssW * device.scale
    const pxH = cssH * device.scale
    const file = `apple-splash-${pxW}-${pxH}-${VERSION}.png`
    const media = `screen and (device-width: ${device.width}px) and (device-height: ${device.height}px) and (-webkit-device-pixel-ratio: ${device.scale}) and (orientation: ${orientation})`
    entries.push({ url: `${PUBLIC_PREFIX}/${file}`, media })
    if (written.has(file)) {
      continue
    }
    written.add(file)
    const mark = await sharp(svg).resize({ width: markCssWidth(cssW) * device.scale }).png().toBuffer()
    await sharp({ create: { width: pxW, height: pxH, channels: 4, background: PWA_LAUNCH_FIELD } })
      .composite([{ input: mark, gravity: 'centre' }])
      .png({ compressionLevel: 9 })
      .toFile(resolve(OUT_DIR, file))
    console.log(`${file}  ${device.name}, ${orientation}`)
  }
}

const sizes = DEVICES.map(({ width, height, scale }) => ({ width, height, scale }))
writeFileSync(CONSTANTS_PATH, `// Generated by scripts/generate-pwa-splash.ts; run it again instead of editing.
export const PWA_STARTUP_IMAGE_VERSION = ${JSON.stringify(VERSION)}

/** One entry per device and orientation for appleWebApp.startupImage. */
export const PWA_STARTUP_IMAGES: { url: string, media: string }[] = ${JSON.stringify(entries, null, 2)}

/** The logical portrait sizes the matrix covers; the device probe checks a phone against them. */
export const PWA_STARTUP_IMAGE_SIZES: { width: number, height: number, scale: number }[] = ${JSON.stringify(sizes, null, 2)}
`)
console.log(`Done. ${written.size} images, ${entries.length} entries.`)
