import { readFileSync, writeFileSync } from 'node:fs'

// One-time generator for the Tri Pros service-area ZIP set. Reads a ZIP→county
// crosswalk at scripts/data/uszips.csv (gitignored build input, columns:
// zip,state_id,county_name) and emits src/shared/constants/company/service-area-zips.ts.
// Re-run after updating the CSV. Pure file IO — no env, no network, no deps.

// Whole-county inclusions (Ventura's western edge IS the city of Ventura, so the
// whole county qualifies — far-north rural ZIPs are trimmed via EXCLUDE below).
const WHOLE_COUNTIES = new Set(['Los Angeles', 'San Bernardino', 'Riverside', 'Ventura', 'Orange'])

// Curated edge trims (boundary cities the user defined).
//  - Orange County south of Laguna Beach: San Clemente, Dana Point, San Juan Capistrano.
//  - Ventura County far-north/rural beyond the city of Ventura: Ojai, Santa Paula, Fillmore, Piru.
const EXCLUDE = new Set([
  '92672',
  '92673',
  '92674', // San Clemente
  '92624',
  '92629', // Dana Point
  '92675',
  '92690',
  '92693', // San Juan Capistrano
  '93023',
  '93024', // Ojai
  '93060',
  '93061', // Santa Paula
  '93015',
  '93016', // Fillmore
  '93040', // Piru
])

// Explicit extra inclusions outside the whole counties.
const EXTRA = new Set(['93560']) // Rosamond (Kern) — north sliver

// Minimal CSV read — the normalized crosswalk has no quoted/embedded-comma
// fields, so a plain split is sufficient (avoids a csv-parse dependency).
const lines = readFileSync('scripts/data/uszips.csv', 'utf8').trim().split('\n')
const header = lines[0].split(',')
const col = {
  zip: header.indexOf('zip'),
  state_id: header.indexOf('state_id'),
  county_name: header.indexOf('county_name'),
}
const rows = lines.slice(1).map((line) => {
  const c = line.split(',')
  return { zip: c[col.zip], state_id: c[col.state_id], county_name: c[col.county_name] }
})

const zips = new Set<string>()
for (const r of rows) {
  const zip = r.zip.padStart(5, '0')
  if (r.state_id === 'CA' && WHOLE_COUNTIES.has(r.county_name) && !EXCLUDE.has(zip)) {
    zips.add(zip)
  }
}
for (const z of EXTRA) {
  zips.add(z)
}

const sorted = [...zips].sort()
const body = `// GENERATED by scripts/generate-service-area-zips.ts — do not edit by hand.\n`
  + `// Tri Pros service area: LA/SB/Riverside/Ventura/Orange counties (whole), minus\n`
  + `// south-of-Laguna OC + far-north Ventura, plus Rosamond (93560). ${sorted.length} ZIPs.\n`
  + `export const SERVICE_AREA_ZIPS: ReadonlySet<string> = new Set([\n${
    sorted.map(z => `  '${z}',`).join('\n')
  }\n])\n`

writeFileSync('src/shared/constants/company/service-area-zips.ts', body)
console.log(`Wrote ${sorted.length} ZIPs to service-area-zips.ts`)
