import type { Metadata, Viewport } from 'next'
import process from 'node:process'
import { Dancing_Script, Nunito, Playfair_Display, Space_Mono, Syne } from 'next/font/google'
import { Providers } from '@/shared/components/providers'
import { PwaSplashScreen } from '@/shared/components/splash-screen/pwa-splash-screen'
import './globals.css'

const playfair = Playfair_Display({
  variable: '--font-serif',
  subsets: ['latin'],
  display: 'swap',
})

const syne = Syne({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap',
})

const dancingScript = Dancing_Script({
  variable: '--font-script',
  subsets: ['latin'],
  display: 'swap',
})

const spaceMono = Space_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
})

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL('https://triprosremodeling.com'),
  title: {
    default: 'Tri Pros Remodeling',
    template: '%s | Tri Pros Remodeling',
  },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  },
  icons: {
    icon: [
      {
        url: '/company/logo/logo-light.svg',
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/company/logo/logo-dark.svg',
        media: '(prefers-color-scheme: dark)',
      },
    ],
    apple: '/pwa/apple-touch-icon.png',
  },
  appleWebApp: {
    capable: true,
    title: 'TPR',
    statusBarStyle: 'black-translucent',
    // Dark solid startup images matched by exact device pixel dimensions —
    // kills the white native launch flash before the app's SVG splash
    // screen takes over post-hydration. Generated by
    // scripts/generate-pwa-splash.ts (sharp). One entry per Apple portrait
    // device; iOS falls back to white if no media query matches, so this
    // list must stay in sync with public/pwa/splash/.
    startupImage: [
      {
        url: '/pwa/splash/apple-splash-640-1136.png',
        media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-750-1334.png',
        media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1242-2208.png',
        media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1125-2436.png',
        media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-828-1792.png',
        media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1242-2688.png',
        media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1170-2532.png',
        media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1284-2778.png',
        media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1179-2556.png',
        media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1290-2796.png',
        media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1206-2622.png',
        media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1320-2868.png',
        media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1536-2048.png',
        media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1620-2160.png',
        media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1640-2360.png',
        media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1668-2224.png',
        media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-1668-2388.png',
        media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
      {
        url: '/pwa/splash/apple-splash-2048-2732.png',
        media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
      },
    ],
  },
  description: 'Family-led residential construction company serving Southern California homeowners. Kitchen and bathroom remodels, ADU construction, garage conversions, and home additions across the San Fernando Valley, San Gabriel Valley, and Greater Los Angeles.',
  authors: [{ name: 'Tri Pros Remodeling' }],
  creator: 'Tri Pros Remodeling',
  publisher: 'Tri Pros Remodeling',
  openGraph: {
    title: 'Tri Pros Remodeling | Kitchen, Bath, ADU & Home Remodeling in SoCal',
    description: 'Family-led residential construction company. Kitchen and bathroom remodels, ADU construction, garage conversions, and home additions across the San Fernando Valley, San Gabriel Valley, and Greater Los Angeles.',
    url: 'https://triprosremodeling.com',
    siteName: 'Tri Pros Remodeling',
    type: 'website',
    locale: 'en_US',
    images: [
      {
        url: '/company/logo/opengraph-image.png',
        width: 1200,
        height: 630,
        alt: 'Tri Pros Remodeling — Kitchen, Bath, ADU and Home Remodeling in Southern California',
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Tri Pros Remodeling | Kitchen, Bath, ADU & Home Remodeling in SoCal',
    description: 'Family-led residential construction company. Kitchen and bathroom remodels, ADU construction, garage conversions, and home additions across the San Fernando Valley, San Gabriel Valley, and Greater Los Angeles.',
    images: ['/company/logo/opengraph-image.png'],
  },
  alternates: {
    canonical: 'https://triprosremodeling.com',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      'index': true,
      'follow': true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export const viewport: Viewport = {
  themeColor: '#03AFED',
  viewportFit: 'cover',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
    >
      <body
        className={`${syne.variable} ${playfair.variable} ${dancingScript.variable} ${spaceMono.variable} ${nunito.className} antialiased`}
      >
        <Providers>
          <PwaSplashScreen />
          {children}
        </Providers>
      </body>
    </html>
  )
}
