import z from 'zod'

import { customerCrud } from '@/shared/entities/customers/dal/server/crud'
import { customerSchemas, customerServerSpec } from '@/shared/entities/customers/lib/server-spec'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { createCustomerBusinessRouter } from './business.router'

export const customersRouter = createEntityRouter(customerServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter. spec.update.jsonbMergeColumns deep-merges
    // the four typed JSONB columns; spec.hooks.delete.before cascades meeting
    // and proposal deletes before the customer row is removed.
    //
    // crud.update is omni-gated: the agent CASL grant on 'Customer' is
    // field-restricted to the three JSON profile columns, but the default
    // createCrudRouter gate (`ability.can('update', 'Customer')` with no field
    // arg) passes for any field-restricted grant — which would let agents
    // bypass per-field CASL on phone / leadSourceId / contact fields via
    // the crud surface. Agents must use business.update* procedures, which
    // preserve their per-field gates. crud.update remains for super-admins
    // and SYSTEM_CONTEXT internal callers.
    crud: createCrudRouter({
      spec: customerServerSpec,
      schemas: { ...customerSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
      handlers: {
        update: async (ctx, input) => {
          if (ctx.ability && !ctx.ability.can('manage', 'all')) {
            return { success: false, error: { type: 'forbidden' } }
          }
          return customerCrud.update(ctx, input)
        },
      },
    }),

    // ── Business queries + entity-specific mutations ────────────────────
    // Hand-coded: list/search/getAll (phone-gated reads), createFromIntake
    // (rate-limited public + multi-step tx), addNote (customer_notes table),
    // updateProfile/updateCreatedAt/updateLeadSource/updateCustomerContact
    // (field-specific CASL + side effects).
    business: createCustomerBusinessRouter(entity),
  })
})
