import type { customerCrud } from '@/shared/entities/customers/dal/server/crud'

import z from 'zod'

import { getCustomer } from '@/shared/entities/customers/dal/server/queries'
import { customerSchemas, customerServerSpec } from '@/shared/entities/customers/lib/server-spec'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { createCustomerBusinessRouter } from './business.router'

export const customersRouter = createEntityRouter(customerServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter. spec.update.jsonbMergeColumns deep-merges
    // the four typed JSONB columns; spec.hooks.delete.before cascades meeting
    // and proposal deletes before the customer row is removed; spec.hooks.update.before
    // resets the geocode cache when address fields change.
    //
    // crud.getById is overridden to return the phone-gated row shape — the
    // default handler from createCrudDal does a plain SELECT * which would
    // include the ungated phone column, violating phone-visibility-threshold.
    // see ../../../shared/entities/customers/DOCS.md#phone-visibility-threshold
    //
    // crud.update uses the framework's field-level CASL enforcement (added in
    // create-crud-router.ts). The agent CASL grant on 'Customer' is field-
    // restricted to the three JSON profile columns; the gate rejects any
    // field outside that allow list automatically.
    crud: createCrudRouter({
      spec: customerServerSpec,
      schemas: { ...customerSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
      handlers: {
        // Cast: getCustomer returns CustomerWithPhoneGate (Customer & { hasSentProposal })
        // which is a structural superset of Row<typeof customers>. The CrudHandlers
        // contract types getById as Row<TTable> | undefined — the extra
        // hasSentProposal field is harmless (callers that don't read it see the
        // standard row shape). The framework-level type for handlers.getById
        // doesn't admit phantom enrichments, so the cast is necessary.
        getById: async (ctx, input) => getCustomer(ctx, input) as ReturnType<typeof customerCrud.getById>,
      },
    }),

    // ── Business queries + entity-specific mutations ────────────────────
    // Hand-coded: list (paginated table), search (phone-gated text search),
    // addNote (writes customer_notes table — different entity), createFromIntake
    // (rate-limited public + multi-step tx). Single-row CRUD mutations live on
    // `crud.*` — agents get there via crud.update (field-CASL-gated), super-
    // admins reach the full surface.
    business: createCustomerBusinessRouter(entity),
  })
})
