import type { customerCrud } from '@/shared/entities/customers/dal/server/crud'

import { TRPCError } from '@trpc/server'
import z from 'zod'

import { customerProfilePatchSchema } from '@/shared/db/schema'
import { upsertCustomerProfile } from '@/shared/entities/customers/dal/server/mutations'
import { getCustomer } from '@/shared/entities/customers/dal/server/queries'
import { customerSchemas, customerServerSpec } from '@/shared/entities/customers/lib/server-spec'
import { dalToTrpc } from '@/trpc/lib/dal-to-trpc'

import { createTRPCRouter } from '../../init'
import { createCrudRouter } from '../../lib/create-crud-router'
import { createEntityRouter } from '../../lib/create-entity-router'
import { createCustomerBusinessRouter } from './business.router'

export const customersRouter = createEntityRouter(customerServerSpec, (entity) => {
  return createTRPCRouter({
    // ── CRUD (5 single-row operations) ──────────────────────────────────
    // Generated by createCrudRouter. spec.hooks.delete.before cascades meeting
    // and proposal deletes before the customer row is removed; spec.hooks.update.before
    // resets the geocode cache when address fields change. (leadMeta jsonbMergeColumns
    // registration was removed in Wave-2 — the blob is frozen; attribution + enrichment
    // are their own child tables now.)
    //
    // crud.getById is overridden to return the phone-gated row shape — the
    // default handler from createCrudDal does a plain SELECT * which would
    // include the ungated phone column, violating phone-visibility-threshold.
    // see ../../../shared/entities/customers/DOCS.md#phone-visibility-threshold
    //
    // crud.update uses the framework's field-level CASL enforcement (added in
    // create-crud-router.ts). The agent CASL grant on 'Customer' is field-
    // restricted to just `age` now (Addendum B, 2026-07-14) — the 23
    // sales-discovery columns moved to the `customer_profiles` child table
    // and go through `profile.upsert` below, gated on the CustomerProfile
    // subject instead.
    crud: createCrudRouter({
      spec: customerServerSpec,
      schemas: { ...customerSchemas, id: z.string().uuid() },
      authedProcedure: entity.authedProcedure,
      shareableProcedure: entity.shareableProcedure,
      handlers: {
        // Cast: getCustomer returns CustomerWithProfile (a structural superset
        // of Row<typeof customers> — phone-gated + flattened-spread joined
        // against customer_profiles). The CrudHandlers contract types getById
        // as Row<TTable> | undefined — the extra fields are harmless (callers
        // that don't read them see the standard row shape). The
        // framework-level type for handlers.getById doesn't admit phantom
        // enrichments, so the cast is necessary.
        getById: async (ctx, input) => getCustomer(ctx, input) as ReturnType<typeof customerCrud.getById>,
      },
    }),

    // ── Profile (customer_profiles 1:1 child table, Addendum B) ─────────
    // Own CASL subject ('CustomerProfile') — different permission boundary
    // than Customer's contact/identity fields. Lazy upsert: row-exists =
    // discovery data has been collected.
    profile: createTRPCRouter({
      upsert: entity.authedProcedure
        .input(z.object({ id: z.string().uuid(), data: customerProfilePatchSchema }))
        .mutation(async ({ ctx, input }) => {
          if (ctx.ability.cannot('update', 'CustomerProfile')) {
            throw new TRPCError({
              code: 'FORBIDDEN',
              message: 'You do not have permission to update the customer profile.',
            })
          }
          return dalToTrpc(await upsertCustomerProfile(ctx, { customerId: input.id, patch: input.data }))
        }),
    }),

    // ── Business queries + entity-specific mutations ────────────────────
    // Hand-coded: list (paginated table), search (phone-gated text search),
    // addNote (writes customer_notes table — different entity), createFromIntake
    // (rate-limited public + multi-step tx). Single-row CRUD mutations live on
    // `crud.*` — agents get there via crud.update (field-CASL-gated), super-
    // admins reach the full surface.
    business: createCustomerBusinessRouter(entity),
  })
})
