import {
  meetingCreditScoreRanges,
  meetingDecisionMakersPresentOptions,
  meetingHouseholdTypes,
  meetingOutcomePriorities,
  meetingPainTypes,
  meetingPriorContractorExperience,
  meetingSellPlans,
  meetingTriggerEvents,
  meetingYearBuiltRanges,
  meetingYearsInHome,
} from '@/shared/constants/enums'

// Field IDs map 1:1 to keys inside the JSONB section specified by jsonbKey.
// `entity` determines whether the field is saved to the meeting or the customer.

export const INTAKE_STEPS = [
  {
    description: 'Understand what is driving them to act and what pain they are trying to solve.',
    fields: [
      {
        entity: 'customer',
        id: 'mainPain',
        jsonbKey: 'customerProfileJSON',
        label: 'Primary pain point',
        options: meetingPainTypes,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'secondaryPain',
        jsonbKey: 'customerProfileJSON',
        label: 'Secondary pain point (if any)',
        options: meetingPainTypes,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'triggerEvent',
        jsonbKey: 'customerProfileJSON',
        label: 'What triggered this visit?',
        options: meetingTriggerEvents,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'outcomePriority',
        jsonbKey: 'customerProfileJSON',
        label: 'What matters most to them?',
        options: meetingOutcomePriorities,
        type: 'select',
      },
    ],
    id: 'pain-motivation',
    title: 'Pain & Motivation',
  },
  {
    description: 'Capture who is at the table and the household makeup. This shapes your entire approach.',
    fields: [
      {
        entity: 'meeting',
        id: 'decisionMakersPresent',
        jsonbKey: 'contextJSON',
        label: 'Who is present today',
        options: meetingDecisionMakersPresentOptions,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'householdType',
        jsonbKey: 'customerProfileJSON',
        label: 'Household type',
        options: meetingHouseholdTypes,
        type: 'select',
      },
    ],
    id: 'household',
    title: 'Household Profile',
  },
  {
    description: 'How long have they been here, what is their plan, and what do we know about the home itself?',
    fields: [
      {
        entity: 'customer',
        id: 'timeInHome',
        jsonbKey: 'customerProfileJSON',
        label: 'Years in this home',
        options: meetingYearsInHome,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'sellPlan',
        jsonbKey: 'customerProfileJSON',
        label: 'Planning to sell?',
        options: meetingSellPlans,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'yearBuilt',
        jsonbKey: 'propertyProfileJSON',
        label: 'Year home was built',
        options: meetingYearBuiltRanges,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'hoa',
        jsonbKey: 'propertyProfileJSON',
        label: 'HOA?',
        type: 'boolean',
      },
    ],
    id: 'home-situation',
    title: 'Home & Situation',
  },
  {
    description: 'Gauge their readiness, how competitive the situation is, and the strength of their commitment.',
    fields: [
      {
        entity: 'customer',
        id: 'numQuotesReceived',
        jsonbKey: 'financialProfileJSON',
        label: 'How many other quotes have they received?',
        min: 0,
        placeholder: '0',
        type: 'number',
      },
      {
        entity: 'customer',
        id: 'projectNecessityRating',
        jsonbKey: 'customerProfileJSON',
        label: 'How necessary is this project to them? (1–10)',
        max: 10,
        min: 1,
        type: 'rating',
      },
      {
        entity: 'customer',
        id: 'constructionOutlookFavorabilityRating',
        jsonbKey: 'customerProfileJSON',
        label: 'How favorable is their outlook on construction? (1–10)',
        max: 10,
        min: 1,
        type: 'rating',
      },
    ],
    id: 'decision-context',
    title: 'Decision Context',
  },
  {
    description: 'Understand their financial picture to tailor the financing conversation.',
    fields: [
      {
        entity: 'customer',
        id: 'creditScore',
        jsonbKey: 'financialProfileJSON',
        label: 'Estimated credit score range',
        options: meetingCreditScoreRanges,
        type: 'select',
      },
      {
        entity: 'customer',
        id: 'priorContractorExperience',
        jsonbKey: 'customerProfileJSON',
        label: 'Prior contractor experience',
        options: meetingPriorContractorExperience,
        type: 'select',
      },
    ],
    id: 'financial',
    title: 'Financial Profile',
  },
]
