export const SPECIALTIES_COPY = {
  heading: 'What areas of your home matter most?',
  introWithLead: 'Start with what they called about. Add anything the walk-through turned up.',
  introNoLead: 'Start with what made them call. Every trade opens its own sheet.',
  catalogLoading: { title: 'Loading trades…', description: 'Fetching the catalog…' },
  catalogError: { title: 'The catalog could not be loaded', description: 'Your selections are kept. Try again.' },
  retry: 'Retry',
  project: {
    eyebrow: 'Project',
    empty: 'Nothing picked yet. Open a trade to start.',
  },
  start: {
    title: 'Nothing requested on this lead.',
    body: 'Pick the trade that made them call. Each one opens its sheet.',
  },
  lead: {
    eyebrow: 'You called about',
    customize: 'Customize',
  },
  catalog: {
    headingWithLead: 'Anything else while we’re here?',
    headingNoLead: 'Every trade',
    hint: 'Tap a trade to open its sheet.',
    searchLabel: 'Filter trades',
    searchPlaceholder: 'Type to filter…',
    noMatches: 'No trades match.',
    scopesToDefine: 'Scopes to define',
  },
  sheet: {
    notOnProject: 'Not on the project yet',
    notInCatalog: 'Not in the current catalog',
    work: 'Work',
    noScopes: 'No scopes in the catalog yet.',
    noScopesAddonsOnly: 'No scopes in the catalog yet. Add-ons only.',
    addons: 'Add-ons',
    reasons: 'Reasons for this work',
    note: 'Note',
    notePlaceholder: (tradeName: string) => `What they said about ${tradeName}…`,
    removeItem: (label: string) => `Remove ${label}`,
    orphanHint: 'Picked earlier, not in the current catalog. Tap one to remove it.',
    pairsWith: 'Pairs well with',
    pairedOnProject: 'is on the project.',
    open: 'Open',
    remove: 'Remove from project',
    done: 'Done',
  },
  units: {
    scope: ['scope', 'scopes'],
    addon: ['add-on', 'add-ons'],
    reason: ['reason', 'reasons'],
    item: ['item', 'items'],
  },
} as const
