export const SPECIALTIES_COPY = {
  heading: 'What areas of your home matter most?',
  catalogLoading: { title: 'Loading trades…', description: 'Fetching the catalog…' },
  catalogError: { title: 'The catalog could not be loaded', description: 'Your selections are kept. Try again.' },
  retry: 'Retry',
  showcase: {
    status: 'On your project',
    projectCaptionLead: 'Tri Pros project',
    ourProjects: 'Our projects',
    included: 'What\'s included',
    scopesToDefine: 'Scopes to define',
  },
  work: {
    regionLabel: 'Choose the work',
    onProject: 'On your project',
    onProjectEmpty: 'Nothing yet. Choose a trade and add the work that fits.',
    tradeLabel: 'Trade',
    switchLabel: 'Choose a trade',
    filterPlaceholder: 'Filter trades…',
    noMatches: 'No trades match.',
    tapToAdd: 'tap to add',
    noWork: (tradeName: string) => `No work to choose yet for ${tradeName}.`,
    add: 'Add to project',
    onYourProject: 'On your project',
    together: 'Often done together',
    togetherPair: (tradeName: string, pairedName: string) => `${tradeName} and ${pairedName}`,
    show: (tradeName: string) => `Show ${tradeName}`,
    groupLabel: (tradeName: string) => `Work for ${tradeName}`,
  },
  panel: {
    heading: 'On the project',
    empty: 'Nothing on the project yet. Add work from the stage.',
    noReason: 'No reason yet',
    noWork: 'No work yet',
    workSummary: (first: string, more: number) => `${first} +${more}`,
    onStage: 'On stage',
    work: 'Work',
    addons: 'Add-ons',
    reasons: 'Reasons',
    editReasons: 'Edit reasons',
    doneEditing: 'Done',
    note: 'Note',
    notePlaceholder: (tradeName: string) => `What they said about ${tradeName}…`,
    showOnStage: 'Show on stage',
    remove: 'Remove from project',
    pairsWith: (pairedName: string, reason: string) => `Pairs with ${pairedName}: ${reason}`,
    show: 'Show',
    notInCatalog: 'Not in the current catalog',
    orphanHint: 'Picked earlier, not in the current catalog. Tap one to remove it.',
    removeItem: (label: string) => `Remove ${label}`,
  },
  undo: {
    tradeRemoved: (tradeName: string) => `${tradeName} is off the project`,
    action: 'Undo',
  },
  start: {
    title: 'Nothing requested on this lead.',
    body: 'Pick the trade that made them call. Each one opens its sheet.',
  },
  lead: {
    eyebrow: 'You called about',
    customize: 'Customize',
  },
  units: {
    scope: ['scope', 'scopes'],
    addon: ['add-on', 'add-ons'],
    reason: ['reason', 'reasons'],
    item: ['item', 'items'],
    work: ['piece of work', 'pieces of work'],
    kind: ['kind of work', 'kinds of work'],
    trade: ['trade', 'trades'],
  },
} as const
